CHECK_ENDPOINT = "/api/models/check"
CREATE_ENDPOINT = "/api/models/create"
HELLO_ENDPOINT = "/api/echo"
LOAD_ENDPOINT = "/api/models/load"
PROCESS_ENDPOINT = "/api/models/process"
TRAIN_ENDPOINT = "/api/models/train"
UNLOAD_ENDPOINT = "/api/models/unload"